CREATE TABLE DUES(
    CUSTOMER_ID VARCHAR(20) DEFAULT'20',
    CUSTOMER_NAME VARCHAR(15) ,
    PHONE VARCHAR(15),
    DUE DECIMAL(10,2),
    PAID DECIMAL(10,2),
    TRANSACTION_ID VARCHAR(20) DEFAULT 'NULL'
);
DROP TABLE DUES;
ALTER TABLE DUES AUTO_INCREMENT = 100;
ALTER TABLE DUES ADD COLUMN TRANSACTION_ID VARCHAR(30) DEFAULT 'NULL' AFTER PAID;
INSERT INTO dues VALUES ('34' ,'SHYKET','182912',12,10,'ABC');
SELECT (PAID-DUE) from DUES WHERE PHONE ="182912";

Select * FROM DUES;
SELECT sum(DUE) FROM DUES;
DROP TRIGGER SET_CID;

DELIMITER |
CREATE TRIGGER SET_CID BEFORE INSERT ON DUES
FOR EACH ROW
BEGIN
DECLARE CUSTOMER_CID INT;
SELECT substring(NEW.PHONE,1,3) INTO CUSTOMER_CID;
SET NEW.CUSTOMER_ID=CUSTOMER_CID;
END;
|

DELIMITER $$
CREATE FUNCTION SET_PROFIT()
RETURNS DECIMAL
DETERMINISTIC
BEGIN
DECLARE RESULT DECIMAL(5,2);
DECLARE A DECIMAL(5,2);
DECLARE B DECIMAL(5,2);
DECLARE CUR CURSOR FOR SELECT DUE,PAID FROM DUES;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

SET RESULT=0.00;
OPEN CUR;

READ_LOOP: LOOP
FETCH CUR INTO A,B;
IF  THEN 
	LEAVE READ_LOOP;
END IF;
SET RESULT=RESULT+B-A;
END LOOP;
CLOSE CUR;	
END$$







