CREATE TABLE NEW_PRODUCT_COUNT(
    PRODUCT_TYPE VARCHAR(30),
    COMPANY_NAME VARCHAR(16),
    PRODUCT_NAME VARCHAR(16),
    AMOUNT INT,
    PRICE DECIMAL(10,2),
    EXPIRING_DATE DATE,
	CHECK ( PRODUCT_TYPE='SNACKS'OR PRODUCT_TYPE= 'SOFTDRINKS'OR PRODUCT_TYPE ='COSMETICS')

);



DROP TABLE NEW_PRODUCT_COUNT;
INSERT INTO NEW_PRODUCT_COUNT VALUES('SOFTDRINKS','PEPSI','PEPSI','8','50.00','2035-12-12');

SELECT * FROM NEW_PRODUCT_COUNT;
DELETE FROM NEW_PRODUCT_COUNT WHERE AMOUNT=8;
SET SQL_SAFE_UPDATES = 0;

SELECT * FROM NEW_PRODUCT_COUNT;
