delimiter |
CREATE  TRIGGER COMPLETE_TABLE AFTER INSERT ON NEW_PRODUCT_COUNT

FOR EACH ROW 
BEGIN
DECLARE NUM INT;
DECLARE UNIQUE_ID INT;
SET NUM =NEW.AMOUNT;

NEWLOOP: LOOP
	SET UNIQUE_ID=CONCAT( NEW.COMPANY_NAME,NUM);
	INSERT INTO product_table SET ID=UNIQUE_ID , PRODUCT_NAME=CONCAT(NEW.COMPANY_NAME,'NICE');
    
    SET NUM=NUM-1;

    IF(NUM=0) THEN leave NEWLOOP;
    end if;
    END LOOP NEWLOOP;
END;
|
delimiter ;

DROP TRIGGER COMPLETE_TABLE;
